version: '3.8'


services:
  db:
    image: postgres:13-alpine
    container_name: database
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - ./data/db_data:/var/lib/postgresql/data/

  web:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && uvicorn api:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    command: bash -c "python3 -m client_simulator"
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - app
    volumes:
      - ./data/client_logs:/app/logs


  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    container_name: worker
    restart: always
    command: bash -c "python3 -m background_processing"
    deploy:
      replicas: 1
    env_file:
      - .env
    depends_on:
      - client
    networks:
      - app
    volumes:
      - ./data/background_log:/app/logs


networks:
  app:
    driver: bridge